apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver-deployment
  labels:
    app: discoveryserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: library-management-discoveryserver
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver
spec:
  selector:
    app: discoveryserver # match with labels
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761 # match with containerPort
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  labels:
    app: apigateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: library-management-apigateway
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway # match with labels
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # match with containerPort
  type: NodePort