server:
  port: 9005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/library-management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: giaihung123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

idp:
  url: http://localhost:8180
  client-id: library-management
  client-secret: KAOcCHjBY53UQGxdodmYE9IRXj3WXZty
  realm: library-management
